.TH dnsip6 1

.SH NAME
dnsip6 \- lookup IPv6 addresses

.SH SYNOPSIS
dnsip6
[
.I fqdn
]

.SH DESCRIPTION
.B dnsip6
resolves
.I fqdn
and prints the IPv6 addresses of
.I fqdn
on a single line.
If
.I fqdn
does not exist,
.B dnsip6
prints a blank line.
You can list several
.IR fqdn s;
.B dnsip6
prints each result on a separate line.

Normally
.B dnsip6
exits 0.
If
.B dnsip6
encounters a temporary problem
that prevents it from determining the list of IPv6 addresses,
it prints an error message and exits 111.
The same comments apply to the other programs described here.

.SH SEE ALSO
dnsip(1),
dnsipq(1),
dnsip6q(1),
dnsname(1),
dnsmx(1),
dnstxt(1),
dnsqr(1),
dnsq(1),
dnstrace(1)

http://cr.yp.to/djbdns.html
